Update app-to-dropbox.yml

diff --git a/.github/workflows/app-to-dropbox.yml b/.github/workflows/app-to-dropbox.yml
--- a/.github/workflows/app-to-dropbox.yml
+++ b/.github/workflows/app-to-dropbox.yml
@@ -8,7 +8,12 @@ on:
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
-
+    inputs:
+     branch:
+        description: "Select branch"
+        required: true
+        default: "master"
+        
 jobs:
   build:
 
@@ -53,6 +58,29 @@ jobs:
         # BUILD_TOOLS_VERSION: "35.0.2"
         BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
 
+    # Rename file
+    - name: Rename file
+      run: |
+          project_name="AAPS"
+          echo "project_name=$project_name" >> $GITHUB_ENV
+          version=$(grep 'const val appVersion' buildSrc/src/main/kotlin/Versions.kt | awk -F'"' '{print $2}' )
+          echo "version=$version" >> $GITHUB_ENV
+          branch=${{ github.event.inputs.branch }}
+          echo "branch=$branch" >> $GITHUB_ENV
+          original_file="app/build/outputs/apk/full/release/app-full-release-unsigned-signed.apk"
+          new_file="app/build/outputs/apk/full/release/${project_name}-${version}_${branch}-app-full-release.apk"
+
+          if [ -f "$original_file" ]; then
+            mv "$original_file" "$new_file"
+            echo "File has been renamed to: $new_file"
+          else
+            echo "Original file not found: $original_file"
+            exit 1
+          fi
+    # List files
+    - name: List files
+      run: ls -l /app/build/outputs/apk/full/release/
+
     # Dropbox Upload
     - name: Upload to Dropbox
       uses: Lewuathe/dropbox-github-action@v1
@@ -60,7 +88,7 @@ jobs:
         dropbox-app-key: ${{ secrets.DROPBOX_APP_KEY }}
         dropbox-app-secret: ${{ secrets.DROPBOX_APP_SECRET }}
         dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
-        source-path: app/build/outputs/apk/full/release/app-full-release-unsigned-signed.apk
-        target-path: /app-full-release-unsigned-signed.apk
+        source-path: app/build/outputs/apk/full/release/${project_name}-${version}_${branch}-app-full-release.apk
+        target-path: /${project_name}-${version}_${branch}-app-full-release.apk
         # source-path: <Path to local file in the github action container space>
         # target-path: <Path to the file in the Dropbox. That is supposed to be under the app folder>
